name: Question
description: Ask a question about the project
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question!
  - type: textarea
    id: description
    attributes:
      label: Question Description
      description: Please describe your question in detail.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the question here.
    validations:
      required: false
